# Generated by Django 4.1.6 on 2023-06-10 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=11)),
                ('additional_phone_number', models.CharField(max_length=11)),
                ('delivery_address', models.CharField(max_length=100)),
                ('additional_info', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
