# Generated by Django 4.1.6 on 2023-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_customeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
