# Generated by Django 4.1.6 on 2023-06-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller-image/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.region'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
